version: "3.0"
services:
  photo-gallery:
    container_name: photo-gallery
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3213:8000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
