version: "3"

services:
  photo-gallery:
    image: ghcr.io/nguyentritai2906/photo-gallery:latest
    container_name: photo_gallery_app
    networks:
      - proxy
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    # ports:
    #   - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - "traefik.http.routers.homepage.rule=Host(`gallery.nttai.io`)"
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.rule=Host(`gallery.nttai.io`)"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - "traefik.http.services.homepage.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
